#ci.gocd.yaml
format_version: 9
environments:
  testing:
    environment_variables:
      DEPLOYMENT: testing
pipelines:
  test-pipeline:
    group: test_group
    display_order: 10
    label_template: "${mygit[:8]}"
    lock_behavior: none
    parameters:
      param1: value1
    materials:
      mygit:
        git: https://github.com/julianorchard/action-test.git
        branch: main
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              resources:
               - "*"
              tasks:
               - exec:
                   command: echo
                   arguments:
                    - "hello world"
