name: GitHub Actions Test

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check file to return environmental
        run: |
          if grep -q "environment = \"production\"" test.tf ; then
            echo "IS_PROD='true'" >> "$GITHUB_ENV"
          else
            echo "IS_PROD='false'" >> "$GITHUB_ENV"
          fi

      - name: Check environment variable
        if: contains(env.IS_PROD, 'true')
        run: echo "It's alive."

      - name: Check environmental variable
        if: contains(env.IS_PROD, 'false')
        run: echo "It's not alive."
