name: GitHub Actions Test

on:
  push:
    branches:
      - main

env:
  TMP_LOCATION: artifacts
  OUTPUT: my_artifact_2

jobs:

  create-artifact:

    runs-on: ubuntu-latest
    steps:

      - name: Create a temporary artifact downloads folder
        run: mkdir $TMP_LOCATION

      - name: Add artifacts to publish to the temp folder
        run: |
          cd $TMP_LOCATION
          mkdir $OUTPUT
          cd $OUTPUT
          echo "test" > test1.txt
          echo "test" > test2.txt
          echo "test" > test3.txt
          cd ..
          # zip $OUTPUT test1.txt test2.txt test3.txt
          cd ..

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.TMP_LOCATION }}
